CREATE TABLE IF NOT EXISTS  SUBJECT
(
	SUBJECT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SUBJECT_NAME	TEXT,
	FACULTY_NAME	TEXT
);
CREATE TABLE IF NOT EXISTS  LECTURES
(
	LECTURE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	LECTURE_DAY	TEXT,
	START_TIME	TIME,
	END_TIME	TIME,
	SUBJECT_ID	INTEGER
);

